version: '3.7'
services:
  db:
    image: postgres:11.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace
      POSTGRES_HOST_AUTH_METHOD: trust