spring:
  profiles:
    active: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/alucard?user=postgres"
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: filesystem:./db/migration
  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true

servlet:
  multipart:
    max-file-size: 30MB
    max-request-size: 30MB

cache:
  jcache:
    provider: org.ehcache.jsr107.EhcacheCachingProvider
    config: classpath:ehcache.xml

server:
  port: 3000
  error:
    include-stacktrace: never

logging:
  level:
    org:
      zalando:
        logbook: INFO
      springframework:
        web: INFO
      camunda:
        bpm:
          client:
            sprint: DEBUG
      hibernate: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %highlight(%-5level) %magenta(%logger.%M) - %msg%n%rEx"

bpm:
  baseUrl: http://localhost:8080/engine-rest
  pollingDelayMs: 5000
  maxTasks: 10
  usePriority: true
  lockDuration: 10000
  workerId: worker_service_task
  endpoints:
    startProcess: /process-definition/key/$processDefinitionKey/start
    fetchAndLock: /external-task/fetchAndLock
    fetchTopicNames: /external-task/topic-names?withLockedTasks=false&withUnlockedTasks=true
    taskVariables: /process-instance/$taskId/variables?deserializeValues=true
    completeTask: /external-task/$taskId/complete
  processDefinitions:
    createModel: CreateModelProcess
    insertModel: InsertModelProcess
    getDocumentsFromModel: GetDocumentsFromModelProcess

kafka:
  bootstrap-address: localhost:9092
  group-id: alucard-group-id
  trusted-packages: com.goodcode.alucard.*
  topics:
    startAction: startActionTopic
    fetchTasks: fetchTasksTopic
    validateActionPermission: validateActionPermissionTopic
    checkIfModelNameExist: checkIfModelNameExistTopic
    createModel: createModelTopic
    notifyFrontEnd: notifyFrontEndTopic
    checkInsertModelValues: checkInsertModelValuesTopic
    registerFieldModelValues: registerFieldModelValuesTopic
    getDocumentsFromModel: getDocumentsFromModelTopic
    startCreateModelInstance: CREATE_MODEL
    startInsertModelInstance: INSERT_MODEL
    startGetDocumentsFromModelInstance: GET_DOCUMENTS_MODEL
